name: stem_laboratory
description: STEM lesson laboratory for grades 5 and 6.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bcrypt: ^1.2.0
  cupertino_icons: ^1.0.9
  file_picker: ^12.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path: ^1.9.1
  pdf: ^3.13.0
  printing: ^5.15.0
  shared_preferences: ^2.5.5
  sqflite: ^2.4.3
  url_launcher: ^6.3.1
  youtube_player_iframe: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf
    - src/data/stem_logo.jpeg
    - src/data/5_class_stem_lesson_ua.json
    - src/data/6_class_stem_lesson_ua.json
    - src/data/5_class_stem_lesson_en.json
    - src/data/6_class_stem_lesson_en.json
    - src/data/users.json
    - src/data/lesson-1-shcho-take-stem-osvita-yaki-buvayut-prof/
    - src/data/lesson-2-shcho-take-proyekt-oznaky-proyektu-rezyu/
    - src/data/lesson-3-shlyakh-do-uspikhu-miy-nayvazhlyvishyy-p/
    - src/data/lesson-25-fotohrafiya-yak-mystetstvo-svitla/
    - src/data/lesson-26-proyekt-namalyuyu-tobi-sontse/
    - src/data/lesson-27-znaky-u-komunikatsiyi-pryrodni-ta-shtuch/
