import '../models.dart';
import 'app_assets.dart';

abstract final class AppStrings {
  static AppLanguage _language = AppLanguage.ukrainian;
  static AppLanguage get language => _language;
  static void setLanguage(AppLanguage value) => _language = value;

  static const _uk = <String, String>{
    'choose': 'Оберіть клас з уроками',
    'class': 'Клас',
    'module': 'Модуль',
    'topic': 'Тема уроку',
    'exercises': 'Вправи',
    'open': 'Відкрити урок',
    'all': 'Усі вправи',
    'none': 'У цьому уроці немає вправ.',
    'quiz': 'Тест',
    'story': 'Історія',
    'competition': 'Змагання',
    'flashcards': 'Картки',
    'diagram': 'Діаграма',
    'rebus': 'Ребус',
    'table': 'Таблиця',
    'text': 'Текст',
    'video': 'Відео',
    'interactiveQuiz': 'Змагання',
    'homework': 'Домашнє завдання',
    'connect': 'З’єднання',
    'watch': 'Відкрити відео',
    'answer': 'Ваша відповідь',
    'loadError': 'Не вдалося завантажити матеріали класу.',
    'noThemes': 'Для цього класу ще немає тем.',
    'login': 'Я вчитель',
    'logout': 'Вийти',
    'email': 'Email',
    'emailHint': 'Введіть email',
    'password': 'Пароль',
    'passwordHint': 'Введіть пароль',
    'loginHelp': 'Використайте дані, надані адміністратором.',
    'invalidCredentials': 'Неправильний email або пароль.',
    'loading': 'Завантаження…',
    'downloadAndroid': 'Завантажити Android APK',
    'downloadError': 'Не вдалося відкрити файл APK.',
    'saveDiagnosticFile': 'Зберегти діагностувальну роботу',
    'downloadDiagnosticError':
        'Не вдалося завантажити файл діагностувальної роботи.',
    'studentVersionNoAnswers': 'Версія для учнів — без відповідей',
    'teacherVersionWithAnswers': 'Версія для вчителя — з відповідями',
    'downloadStudentPdf': 'Завантажити PDF',
    'downloadTeacherPdf': 'Завантажити PDF з відповідями',
    'allExercises': 'Показати всі вправи',
    'oneByOne': 'По одній',
    'previous': 'Назад',
    'next': 'Далі',
    'downloadPdf': 'Завантажити PDF',
    'printPdf': 'Друкувати PDF',
    'pdfError': 'Не вдалося створити PDF уроку.',
    'correctAnswer': 'Правильна відповідь',
    'yourChoice': 'Ваш вибір',
    'showSolution': 'Показати розв’язок',
    'hideSolution': 'Сховати розв’язок',
    'createProposal': 'Запропонувати урок або вправу',
    'newLesson': 'Новий урок',
    'newExercise': 'Нова вправа',
    'selectTheme': 'Оберіть тему',
    'selectLesson': 'Оберіть урок',
    'title': 'Назва',
    'id': 'Ідентифікатор',
    'type': 'Тип',
    'formats': 'Формати',
    'solution': 'Розв’язок (необов’язково)',
    'content': 'Текст',
    'questions': 'Питання',
    'columns': 'Колонки',
    'rows': 'Рядки',
    'dataToFill': 'Дані для заповнення',
    'youtubeUrl': 'YouTube URL',
    'leftItems': 'Елементи ліворуч',
    'rightItems': 'Елементи праворуч',
    'save': 'Зберегти',
    'submitProposal': 'Створити пропозицію',
    'preview': 'JSON пропозиції',
    'proposalSaved': 'Пропозицію збережено.',
    'addQuestion': 'Додати питання',
    'addExercise': 'Додати вправу',
    'image': 'Зображення',
    'chooseImage': 'Обрати зображення',
    'connectChooseFirst': 'Оберіть елемент з першої колонки',
    'connectChooseSecond': 'Оберіть відповідний елемент',
    'connectCorrect': 'Правильно',
    'connectWrong': 'Неправильно',
    'correctPairs': 'Правильних пар',
    'language': 'Мова',
    'horizontal': 'Горизонтально',
    'vertical': 'Вертикально',
    'singleChoiceOptions': 'Варіанти відповідей (по одному на рядок)',
    'trueFalse': 'Правда / неправда',
  };

  static const _en = <String, String>{
    'choose': 'Choose a class with lessons',
    'class': 'Class',
    'module': 'Module',
    'topic': 'Lesson topic',
    'exercises': 'Exercises',
    'open': 'Open lesson',
    'all': 'All exercises',
    'none': 'There are no exercises in this lesson.',
    'quiz': 'Quiz',
    'story': 'Story',
    'competition': 'Competition',
    'flashcards': 'Flashcards',
    'diagram': 'Diagram',
    'rebus': 'Rebus',
    'table': 'Table',
    'text': 'Text',
    'video': 'Video',
    'interactiveQuiz': 'Competition',
    'homework': 'Homework',
    'connect': 'Connect',
    'watch': 'Open video',
    'answer': 'Your answer',
    'loadError': 'Could not load class materials.',
    'noThemes': 'There are no themes for this class yet.',
    'login': 'I am a teacher',
    'logout': 'Log out',
    'email': 'Email',
    'emailHint': 'Enter email',
    'password': 'Password',
    'passwordHint': 'Enter password',
    'loginHelp': 'Use credentials supplied by the administrator.',
    'invalidCredentials': 'Incorrect email or password.',
    'loading': 'Loading…',
    'downloadAndroid': 'Download Android APK',
    'downloadError': 'Could not open the APK file.',
    'saveDiagnosticFile': 'Save diagnostic work',
    'downloadDiagnosticError': 'Could not download the diagnostic work file.',
    'studentVersionNoAnswers': 'Student version — without answers',
    'teacherVersionWithAnswers': 'Teacher version — with answers',
    'downloadStudentPdf': 'Download PDF',
    'downloadTeacherPdf': 'Download PDF with answers',
    'allExercises': 'Show all exercises',
    'oneByOne': 'One by one',
    'previous': 'Previous',
    'next': 'Next',
    'downloadPdf': 'Download PDF',
    'printPdf': 'Print PDF',
    'pdfError': 'Could not create the lesson PDF.',
    'correctAnswer': 'Correct answer',
    'yourChoice': 'Your choice',
    'showSolution': 'Show solution',
    'hideSolution': 'Hide solution',
    'createProposal': 'Propose a lesson or exercise',
    'newLesson': 'New lesson',
    'newExercise': 'New exercise',
    'selectTheme': 'Select theme',
    'selectLesson': 'Select lesson',
    'title': 'Title',
    'id': 'Identifier',
    'type': 'Type',
    'formats': 'Formats',
    'solution': 'Solution (optional)',
    'content': 'Text',
    'questions': 'Questions',
    'columns': 'Columns',
    'rows': 'Rows',
    'dataToFill': 'Data to fill',
    'youtubeUrl': 'YouTube URL',
    'leftItems': 'Left items',
    'rightItems': 'Right items',
    'save': 'Save',
    'submitProposal': 'Create proposal',
    'preview': 'Proposal JSON',
    'proposalSaved': 'Proposal saved.',
    'addQuestion': 'Add question',
    'addExercise': 'Add exercise',
    'image': 'Image',
    'chooseImage': 'Choose image',
    'connectChooseFirst': 'Choose an item from the first column',
    'connectChooseSecond': 'Choose the matching item',
    'connectCorrect': 'Correct',
    'connectWrong': 'Wrong',
    'correctPairs': 'Correct pairs',
    'language': 'Language',
    'horizontal': 'Horizontal',
    'vertical': 'Vertical',
    'singleChoiceOptions': 'Answer choices (one per line)',
    'trueFalse': 'True / false',
  };

  static String get(String key) {
    final strings = _language == AppLanguage.ukrainian ? _uk : _en;
    return strings[key] ?? key;
  }

  static String format(LessonFormat format) => get(format.jsonValue);
  static String exerciseType(ExerciseType type) => get(type.name);
}
